package MyTest::Control::Container::Minimal::CFirst;

use strict;
use warnings;

use Class::Std::Storable;
use base qw(MyTest::Control::Container::Minimal::_CFirst);

1;

__END__

=pod

=head1 NAME

MyTest::Control::Container::Minimal::CFirst - auto-generated by Hyper Framework

=head1 DESCRIPTION

All functionality is inherited from 
MyTest::Control::Container::Minimal::_CFirst


Override methods by re-implementing them here if needed.

=head1 COPYING


=head1 AUTHOR

 Generated by Hyper::Generator::Control

=cut
