package MyTest::Control::Container::Minimal::CSecond;

use strict;
use warnings;

use Class::Std::Storable;
use base qw(MyTest::Control::Container::Minimal::_CSecond);

1;

__END__

=pod

=head1 NAME

MyTest::Control::Container::Minimal::CSecond - auto-generated by Hyper Framework

=head1 DESCRIPTION

All functionality is inherited from 
MyTest::Control::Container::Minimal::_CSecond


Override methods by re-implementing them here if needed.

=head1 COPYING


=head1 AUTHOR

 Generated by Hyper::Generator::Control

=cut
